# Generated by Django 4.0.2 on 2023-03-20 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='license',
            old_name='created',
            new_name='reserved',
        ),
    ]
